spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    social:
        facebook:
            appId: 487654301400466
            appSecret: 3ec76bf19fbfeaf187a6673d1cf16411
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:mariadb://52.40.188.249:3306/dashboard
        username: rhkdgh27
        password: dltnstls27
        driverClassName: org.mariadb.jdbc.Driver
        platform: mariadb
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        time-zone : Asia/Seoul
#        deserialization:
#            unwrap-root-value: true
#        serialization:
#            wrap-root-value: true

logging:
    level:
        com.millky.blog: DEBUG

server:
    error:
        whitelabel:
            enabled: false
