spring:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

logging:  
    level:  
     com.JGH: DEBUG  
#    jpa:
#        database: MySQL5InnoDBDialect


#    datasource:
#        url: jdbc:mariadb://52.40.188.249:3306/dashboard
#        username: rhkdgh27
#        password: dltnstls27
#        driverClassName: org.mariadb.jdbc.Driver
#        platform: mariadb

        